media: assets
content: 
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: description, label: Description, type: string, options: { maxlenght: 160 } }
      - { name: icon, label: Icon, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: cover, label: Preview image, type: image, description: Img for link preview }
  - name: homepage
    label: Homepage
    path: 'glavnaya-1.md'
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: description, label: Description, type: string, options: { maxlenght: 160 } }
      - { name: icon, label: Icon, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: cover, label: Preview image, type: image, description: Img for link preview }