media: assets
content: 
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: description, label: Description, type: string, options: { maxlenght: 160 } }
      - { name: icon, label: Icon, type: string }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }