name: Update IPs and Publish

on:
  push:
    branches:
      - main

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install curl and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Fetch data and save to response.txt
      run: |
        curl -s https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips -o RAWcloudfront.txt

    - name: Extract IPs and save
      run: |
        grep -oP '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(\/\d{1,2})?\b' RAWcloudfront.txt > ClFrntips.txt
        rm RAWcloudfront.txt

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update IPs'
        add: 'ClFrntips.txt RAWcloudfront.txt'
        push: true
