name: Get Domain addr

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:

  dns-lookup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: DNS Lookup
      run: |
        touch outputipv4.txt
        target = "plugins.jetbrains.com"
        dns_servers=("8.8.8.8" "1.1.1.1" "9.9.9.9" "8.8.4.4" "77.88.8.8" "77.88.8.88" "208.67.222.222" "208.67.220.220" "193.58.251.251" "8.26.56.26" "8.20.247.20" "1.0.0.1" "64.6.64.6" "185.228.168.9" "185.228.169.9" "176.103.130.130" "176.103.130.131" "198.101.242.72" "23.253.163.53" "168.119.61.220" "132.226.205.6" "54.93.169.181" "161.97.94.229")
        for server in "${dns_servers[@]}"; do
          dig +short @$server $target >> ips.txt
          sort ips.txt | uniq >> outputipv4.txt
          rm ips.txt
        done
        
    - name: Upload output.txt
      uses: actions/upload-artifact@v3
      with:
        name: outputipv4
        path: outputipv4.txt
